version: '1.0'
services:
   keycloak:
      container_name: 'Keycloak'
      image: 'ghcr.io/identicum/keycloak:19.0.3-legacy'
      restart: always # https://docs.docker.com/reference/cli/docker/compose/restart/ - Hot reload del yaml
      ports:
         - 8080:8080 #El rango me lo toma desde:hasta, por lo tanto si quiero un puerto especifico limito el rango a si mismo.
      env_file: '.env'
