version: '1.0'
services:
   keycloak:
      container_name: 'Keycloak'
      image: 'ghcr.io/identicum/keycloak:23.0.7'
      restart: always # https://docs.docker.com/reference/cli/docker/compose/restart/ - Hot reload del yaml
      ports:
         - 8080:8080 #El rango me lo toma desde:hasta, por lo tanto si quiero un puerto especifico limito el rango a si mismo.
      command: start-dev
      depends_on:
         - db
      environment:
         KEYCLOAK_ADMIN: admin
         KEYCLOAK_ADMIN_PASSWORD: admin
         KC_DB: postgres
         KC_DB_URL: jdbc:postgresql://db:5432/test
         KC_DB_USERNAME: admin
         KC_DB_PASSWORD: admin

   #DOCS https://hub.docker.com/_/postgres
   db:
      container_name: db
      image: 'postgres:15'
      ports:
         - 5432:5432 #El rango me lo toma desde:hasta, por lo tanto si quiero un puerto especifico limito el rango a si mismo.
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin
         POSTGRES_DB: test
