version: '1.0'
services:
   keycloak:
      container_name: 'Keycloak'
      image: 'ghcr.io/identicum/keycloak:23.0.7'
      restart: always # https://docs.docker.com/reference/cli/docker/compose/restart/ - Hot reload del yaml
      ports:
         - 8080:8080 #El rango me lo toma desde:hasta, por lo tanto si quiero un puerto especifico limito el rango a si mismo.
      command: start-dev --import-realm
      depends_on:
         - db
      environment:
         KEYCLOAK_ADMIN: admin
         KEYCLOAK_ADMIN_PASSWORD: admin
         KC_DB: postgres
         KC_DB_URL: jdbc:postgresql://db:5432/test
         KC_DB_USERNAME: admin
         KC_DB_PASSWORD: admin
         #REST API
         JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.admin2=disabled
         #KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
         KC_SPI_THEME_DEFAULT: 'my-theme'
      volumes:
         - ./config/keycloak1/target/keycloak-rest-repo.jar:/opt/keycloak/providers/keycloak-rest-repo.jar
         - ./config/keycloak1/startup-scripts/:/opt/keycloak/providers/startup-scripts/
         - ./config/keycloak1/custom-scripts/:/opt/keycloak/providers/custom-scripts/
         - ./config/keycloak1/objects/:/opt/keycloak/providers/objects/
         - ./config/keycloak1/objects/realm.json:/opt/keycloak/data/import/realm.json
         - ./config/keycloak1/themes/:/opt/keycloak/themes/
         # - ./keycloak-rest-repo/objects/components/rest-repo.json:/opt/keycloak/data/import/rest-repo.json

   #DOCS https://hub.docker.com/_/postgres
   db:
      container_name: db
      image: 'postgres:15'
      ports:
         - 5432:5432 #El rango me lo toma desde:hasta, por lo tanto si quiero un puerto especifico limito el rango a si mismo.
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin
         POSTGRES_DB: test

   rest-users-api:
      container_name: rest-users-api
      pull_policy: always
      restart: always
      image: 'ghcr.io/identicum/rest-users-api:latest'
      ports:
         - 8081:8081 #El rango me lo toma desde:hasta, por lo tanto si quiero un puerto especifico limito el rango a si mismo.
