version: '2'
services:
  web1:
    image: nginx:alpine
    container_name: web1
    restart: always
    volumes:
      - ./web1/html/:/usr/share/nginx/html/
      - ./web1/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80

  web2:
    image: nginx:alpine
    container_name: web2
    restart: always
    volumes:
      - ./web2/:/usr/share/nginx/html/
    ports:
      - 8082:80

  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_LOG_LEVEL=debug